### ISSUE TITLE
Unresponsive during long-running scripts

### ISSUE THREAD

**Issue by itskaizad** [DanielFiller30/ScriptManager#13]
The tool does not let you run a script while another long-running script is running.
If I use a preset to run a simulator (which it does) I cannot then run another command to install binaries, etc until the simulator is killed. 
Allowing scripts to not wait for success/failure would be very useful!

**Comment by DanielFiller30** [comment]
With the new version (V3) of ScriptManager, parallel execution of scripts is possible. 
Feel free to test it out. 🎉
