### ISSUE TITLE
No way to kill a command

### ISSUE THREAD

**Issue by itskaizad** [DanielFiller30/ScriptManager#17]
Long-running commands like ssh port forwarding run forever but eventually get killed by the system (put the system to sleep, etc). ScriptManager still shows the command as 'processing'.
The ability to force kill a command that hasn't 'finished' yet would be great to overcome limitations with such commands.

MacOS 14.3.1 with ScriptManager v3

**Comment by DanielFiller30** [comment]
With the new version V4 it is possible to cancel running scripts. 🤩
